[workspace]
members = [
    "onchain/programs/random_guard",
]

[programs.localnet]
random_guard = "EZY8pKMU8Xmasm91dhb5hgW6zRFwm5M4vBCntt6iHkjT"

[programs.devnet]
random_guard = "EZY8pKMU8Xmasm91dhb5hgW6zRFwm5M4vBCntt6iHkjT"

[provider]
cluster = "mainnet"
wallet = "/Users/samskirrow/.config/solana/devnet.json"

[registry]
url = "https://api.apr.dev"